create table if not exists CLIENT_TBL (
  ID integer generated by default as identity,
  NAME varchar(40),
  ADDRESS varchar(50),
  MANAGER_ID integer,
  STATUS boolean not null default true,
    primary key (ID)
);

create table if not exists MANAGER_TBL (
  ID integer generated by default as identity,
  SURNAME varchar(20),
  NAME varchar(20),
  MIDDLENAME varchar(20),
  PHONE varchar(20),
  ASSISTANT integer,
  STATUS boolean not null default true,
  primary key (ID)
);

alter table CLIENT_TBL
  add constraint FK_MANAGER_ID
foreign key (MANAGER_ID)
references MANAGER_TBL;

alter table MANAGER_TBL
  add constraint FK_ASSISTANT
foreign key (ASSISTANT)
references MANAGER_TBL;